<%@ page contentType="text/html; charset=euc-kr" %>
<%

	String service                 = request.getParameter("service");
	String noti_url                = request.getParameter("noti_url");
	String noti_date               = request.getParameter("noti_date");
	String noti_time               = request.getParameter("noti_time");
	String noti_term               = request.getParameter("noti_term");
	String noti_cnt                = request.getParameter("noti_cnt");
	String noti_code               = request.getParameter("noti_code");
	String trans_seq               = request.getParameter("trans_seq");
	String shop_seq                = request.getParameter("shop_seq");
	String shop_code               = request.getParameter("shop_code");
	String user_id                 = request.getParameter("user_id");
	String user_name               = request.getParameter("user_name");
	String user_phone_no           = request.getParameter("user_phone_no");
	String moid                    = request.getParameter("moid");
	String goods_name              = request.getParameter("goods_name");
	String goods_amt               = request.getParameter("goods_amt");
	String buyer_name              = request.getParameter("buyer_name");
	String buyer_code              = request.getParameter("buyer_code");
	String buyer_phone_no          = request.getParameter("buyer_phone_no");
	String buyer_email             = request.getParameter("buyer_email");
	String pg_code                 = request.getParameter("pg_code");
	String pg_name                 = request.getParameter("pg_name");
	String pay_method              = request.getParameter("pay_method");
	String pay_method_name         = request.getParameter("pay_method_name");
	String pg_mid                  = request.getParameter("pg_mid");
	String pg_sid                  = request.getParameter("pg_sid");
	String status                  = request.getParameter("status");
	String status_name             = request.getParameter("status_name");
	String cash_receipt_type       = request.getParameter("cash_receipt_type");
	String cash_receipt_type_name  = request.getParameter("cash_receipt_type_name");
	String cash_receipt_no         = request.getParameter("cash_receipt_no");
	String cash_receipt_supply_amt = request.getParameter("cash_receipt_supply_amt");
	String cash_receipt_vat        = request.getParameter("cash_receipt_vat");
	String zone_code               = request.getParameter("zone_code");
	String address                 = request.getParameter("address");
	String address_detail          = request.getParameter("address_detail");
	String comment                 = request.getParameter("comment");
	String recipient_name          = request.getParameter("recipient_name");
	String recipient_phone_no      = request.getParameter("recipient_phone_no");
	String pg_req_date             = request.getParameter("pg_req_date");
	String pg_req_time             = request.getParameter("pg_req_time");
	String pg_result_code          = request.getParameter("pg_result_code");
	String pg_result_msg           = request.getParameter("pg_result_msg");
	String pg_app_date             = request.getParameter("pg_app_date");
	String pg_app_time             = request.getParameter("pg_app_time");
	String pg_tid                  = request.getParameter("pg_tid");
	String card_no                 = request.getParameter("card_no");
	String card_quota              = request.getParameter("card_quota");
	String card_issue_code         = request.getParameter("card_issue_code");
	String card_issue_name         = request.getParameter("card_issue_name");
	String card_acquire_code       = request.getParameter("card_acquire_code");
	String card_acquire_name       = request.getParameter("card_acquire_name");
	String approval_amt            = request.getParameter("approval_amt");
	String approval_no             = request.getParameter("approval_no");
	String cancel_amt              = request.getParameter("cancel_amt");
	String cancel_msg              = request.getParameter("cancel_msg");
	String cancel_req_date         = request.getParameter("cancel_req_date");
	String cancel_req_time         = request.getParameter("cancel_req_time");
	String cancel_result_code      = request.getParameter("cancel_result_code");
	String cancel_result_msg       = request.getParameter("cancel_result_msg");
	String cancel_app_date         = request.getParameter("cancel_app_date");
	String cancel_app_time         = request.getParameter("cancel_app_time");
	String cancel_pg_tid           = request.getParameter("cancel_pg_tid");
	String cancel_approval_amt     = request.getParameter("cancel_approval_amt");
	String cancel_approval_no      = request.getParameter("cancel_approval_no");

	System.out.println("service [" + service + "]");
	System.out.println("noti_url [" + noti_url + "]");
	System.out.println("noti_date [" + noti_date + "]");
	System.out.println("noti_time [" + noti_time + "]");
	System.out.println("noti_term [" + noti_term + "]");
	System.out.println("noti_cnt [" + noti_cnt + "]");
	System.out.println("noti_code [" + noti_code + "]");
	System.out.println("trans_seq [" + trans_seq + "]");
	System.out.println("shop_seq [" + shop_seq + "]");
	System.out.println("shop_code [" + shop_code + "]");
	System.out.println("user_id [" + user_id + "]");
	System.out.println("user_name [" + user_name + "]");
	System.out.println("user_phone_no [" + user_phone_no + "]");
	System.out.println("moid [" + moid + "]");
	System.out.println("goods_name [" + goods_name + "]");
	System.out.println("goods_amt [" + goods_amt + "]");
	System.out.println("buyer_name [" + buyer_name + "]");
	System.out.println("buyer_code [" + buyer_code + "]");
	System.out.println("buyer_phone_no [" + buyer_phone_no + "]");
	System.out.println("buyer_email [" + buyer_email + "]");
	System.out.println("pg_code [" + pg_code + "]");
	System.out.println("pg_name [" + pg_name + "]");
	System.out.println("pay_method [" + pay_method + "]");
	System.out.println("pay_method_name [" + pay_method_name + "]");
	System.out.println("pg_mid [" + pg_mid + "]");
	System.out.println("pg_sid [" + pg_sid + "]");
	System.out.println("status [" + status + "]");
	System.out.println("status_name [" + status_name + "]");
	System.out.println("cash_receipt_type [" + cash_receipt_type + "]");
	System.out.println("cash_receipt_type_name [" + cash_receipt_type_name + "]");
	System.out.println("cash_receipt_no [" + cash_receipt_no + "]");
	System.out.println("cash_receipt_supply_amt [" + cash_receipt_supply_amt + "]");
	System.out.println("cash_receipt_vat [" + cash_receipt_vat + "]");
	System.out.println("zone_code [" + zone_code + "]");
	System.out.println("address [" + address + "]");
	System.out.println("address_detail [" + address_detail + "]");
	System.out.println("comment [" + comment + "]");
	System.out.println("recipient_name [" + recipient_name + "]");
	System.out.println("recipient_phone_no [" + recipient_phone_no + "]");
	System.out.println("pg_req_date [" + pg_req_date + "]");
	System.out.println("pg_req_time [" + pg_req_time + "]");
	System.out.println("pg_result_code [" + pg_result_code + "]");
	System.out.println("pg_result_msg [" + pg_result_msg + "]");
	System.out.println("pg_app_date [" + pg_app_date + "]");
	System.out.println("pg_app_time [" + pg_app_time + "]");
	System.out.println("pg_tid [" + pg_tid + "]");
	System.out.println("card_no [" + card_no + "]");
	System.out.println("card_quota [" + card_quota + "]");
	System.out.println("card_issue_code [" + card_issue_code + "]");
	System.out.println("card_issue_name [" + card_issue_name + "]");
	System.out.println("card_acquire_code [" + card_acquire_code + "]");
	System.out.println("card_acquire_name [" + card_acquire_name + "]");
	System.out.println("approval_amt [" + approval_amt + "]");
	System.out.println("approval_no [" + approval_no + "]");
	System.out.println("cancel_amt [" + cancel_amt + "]");
	System.out.println("cancel_msg [" + cancel_msg + "]");
	System.out.println("cancel_req_date [" + cancel_req_date + "]");
	System.out.println("cancel_req_time [" + cancel_req_time + "]");
	System.out.println("cancel_result_code [" + cancel_result_code + "]");
	System.out.println("cancel_result_msg [" + cancel_result_msg + "]");
	System.out.println("cancel_app_date [" + cancel_app_date + "]");
	System.out.println("cancel_app_time [" + cancel_app_time + "]");
	System.out.println("cancel_pg_tid [" + cancel_pg_tid + "]");
	System.out.println("cancel_approval_amt [" + cancel_approval_amt + "]");
	System.out.println("cancel_approval_no [" + cancel_approval_no + "]");
	
	out.print("0000");

%>
